export const catalogo = [
    {
      id: 1,
      marca: "Zara",
      nome: "Camisa Larga com Bolsos",
      preco: 70,
      imagem: "product-1.jpg",
    },
    {
      id: 2,
      marca: "Zara",
      nome: "Casaco Reto com Lã",
      preco: 85,
      imagem: "product-2.jpg",
    },
    {
      id: 3,
      marca: "Zara",
      nome: "Jaqueta com Feito Camurça",
      preco: 60,
      imagem: "product-3.jpg",
    },
    {
      id: 4,
      marca: "Zara",
      nome: "Sobretudo em Mescla de Lã",
      preco: 160,
      imagem: "product-4.jpg",
    },
    {
      id: 5,
      marca: "Zara",
      nome: "Camisa Larga Acolchoada de Veludo Colete",
      preco: 110,
      imagem: "product-5.jpg",
    },
    {
      id: 6,
      marca: "Zara",
      nome: "Casaco de Lã com Botões",
      preco: 170,
      imagem: "product-6.jpg",
    },
    {
      id: 7,
      marca: "Zara",
      nome: "Casaco com Botões",
      preco: 75,
      imagem: "product-7.jpg",
    },
    {
      id: 8,
      marca: "Zara",
      nome: "Colete Comprido com Cinto",
      preco: 88,
      imagem: "product-8.jpg",
    },
  ];